[package]
name = "serde-bench"
version = "0.0.2"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Minimal serialization format for benchmarking Serde"
repository = "https://github.com/serde-rs/bench"
documentation = "https://docs.rs/serde-bench/"
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
byteorder = "1.0"
serde = "0.9"
